version: '3.3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:5.1.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "localhost: 127.0.0.1"
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3

  kafka:
    image: confluentinc/cp-kafka:5.1.0
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_HEAP_OPTS: "-Xmx4g"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_SOCKET_REQUEST_MAX_BYTES: 2000000000
    extra_hosts:
      - "localhost: 127.0.0.1"
    healthcheck:
      test: echo stat | nc localhost 9092
      interval: 10s
      timeout: 10s
      retries: 3

  schemaregistry:
    image: confluentinc/cp-schema-registry:5.1.0
    ports:
      - 8081:8081
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:9092'
    extra_hosts:
      - "localhost: 127.0.0.1"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://schemaregistry:8081"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  payment:
    build: .
    image: mytaxiapp:latest
    depends_on:
      - kafka
      - schemaregistry

  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"
    restart: always
    volumes:
      - ./out/cassandra_data:/var/lib/cassandra
      - ./cassandra-init.sh:/cassandra-init.sh
    command: "sh /cassandra-init.sh"
    healthcheck:
      test: echo stat | nc localhost 9042
      interval: 10s
      timeout: 10s
      retries: 3

#    cassandra-load-keyspace:
#        container_name: cassandra-load-keyspace
#        image: cassandra:latest
#        depends_on:
#          - cassandra
#        volumes:
#          - ./schema.cql:/schema.cql
#        command: /bin/bash -c "sleep 60 && echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql; exit 0"


#  payment:
#    build: paymentservice/.
#    image: producer:latest
#    depends_on:
#      - kafka
#      - schemaregistry


#  paymentsconsumer:
#    build: MyTaxiPaymentsConsumer/.
#    image: consumer:latest
#    depends_on:
#      - kafka
#      - schemaregistry
